# Generated by Django 5.2.1 on 2025-05-18 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_applications",
            field=models.ManyToManyField(
                blank=True,
                help_text="ユーザーがアクセスを許可されているクライアントアプリケーション",
                related_name="allowed_users",
                related_query_name="allowed_user",
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
            ),
        ),
    ]
